import './globals.css'
import { Inter } from 'next/font/google'
import NavigationBoard from '@/components/NavigationBoard';
import Header from '@/components/Header';
import { Box } from '@mui/material';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Box sx={{ display: 'flex', height: '100vh', overflow: 'hidden' }}>
          <Box sx={{ width: 272, flexShrink: 0 }}>
            <NavigationBoard />
          </Box>
          <Box sx={{ flexGrow: 1, display: 'flex', flexDirection: 'column' }}>
            <Header />
            <Box
              sx={{
                flexGrow: 1,
                padding: 2,
                backgroundColor: '#1c1c1c',
                overflowY: 'auto',
                '::-webkit-scrollbar': { display: 'none' },
                msOverflowStyle: 'none',
                scrollbarWidth: 'none',
              }}
            >
              <Box sx={{ marginX: 1.5 }}>
                {children}
              </Box>
            </Box>
          </Box>
        </Box>
      </body>
    </html>
  )
}
