import "./globals.css";
import { Inter } from "next/font/google";
import NavigationBoard from "@/components/core/NavigationBoard";
import Header from "@/components/Header";
import { Grid, Container, Stack } from "@mui/material";
import StoreProvider from "./store-provider";
import ThemeProvider from "./theme-provider";
import Sidebar from "@/components/core/Sidebar";
import LocalizationProvider from "./localization-provider";
import AlertProvider from "./alert_provider";
import {useRouter} from "next/navigation";
import {useEffect} from "react";
import {headers} from "next/headers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const requestUrl: string = headers().get('x-url') ?? "";
  const isLoginPage = requestUrl.includes("auth");
  console.log(requestUrl);
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <StoreProvider>
            <LocalizationProvider>
              <AlertProvider>
                {!isLoginPage ? (<Grid container>
                  <Grid
                    item
                    xs={2}
                    md={2}
                    style={{ position: "sticky", minHeight: "100vh" }}
                  >
                    <Sidebar />
                  </Grid>
                  <Grid
                    item
                    xs={10}
                    md={10}
                    style={{ backgroundColor: "#1C1C1C" }}
                  >
                    <Header />
                    <Container
                      maxWidth="xl"
                      sx={{
                        py: "20px",
                      }}
                    >
                      {children}
                    </Container>
                  </Grid>
                </Grid>) : (<>{children}</>)}
              </AlertProvider>
            </LocalizationProvider>
          </StoreProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
