import "./globals.css";
import { Inter } from "next/font/google";
import NavigationBoard from "@/components/core/NavigationBoard";
import Header from "@/components/Header";
import { Grid, Container, Stack } from "@mui/material";
import StoreProvider from "./store-provider";
import ThemeProvider from "./theme-provider";
import Sidebar from "@/components/core/Sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <StoreProvider>
            <Grid container>
              <Grid
                item
                xs={2}
                md={2}
                style={{ position: "sticky", minHeight: "100vh" }}
              >
                <Sidebar />
              </Grid>
              <Grid item xs={10} md={10} style={{ backgroundColor: "#1C1C1C" }}>
                <Header />
                <Container
                  maxWidth="xl"
                  sx={{
                    py: "20px",
                  }}
                >
                  <Stack gap={2}>{children}</Stack>
                </Container>
              </Grid>
            </Grid>
          </StoreProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
