//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package models

import (
	"time"
)

type ExternalShop struct {
	IDExternalShop int32     `sql:"primary_key" json:"id_external_shop" xml:"id_external_shop"`
	FkShop         *int32    `json:"fk_shop" xml:"fk_shop"`
	FkEcommerce    int32     `json:"fk_ecommerce" xml:"fk_ecommerce"`
	Name           string    `json:"name" xml:"name"`
	Status         string    `json:"status" xml:"status"`
	CreatedAt      time.Time `json:"created_at" xml:"created_at"`
	UpdatedAt      time.Time `json:"updated_at" xml:"updated_at"`
}
