//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package models

import (
	"time"
)

type ShopifyExternalShopAuth struct {
	IDShopifyExternalShopAuth int32     `sql:"primary_key" json:"id_shopify_external_shop_auth" xml:"id_shopify_external_shop_auth"`
	FkExternalShop            int32     `json:"fk_external_shop" xml:"fk_external_shop"`
	Name                      string    `json:"name" xml:"name"`
	AccessToken               *string   `json:"access_token" xml:"access_token"`
	CreatedAt                 time.Time `json:"created_at" xml:"created_at"`
}
