//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package models

import (
	"time"
)

type UserShopifyAuth struct {
	IDUserShopifyAuth int32 `sql:"primary_key"`
	FkUser            int32
	ShopName          string
	ClientID          string
	ClientSecret      string
	AccessToken       string
	CreatedAt         time.Time
}
