//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package models

type User struct {
	IDUser int32 `sql:"primary_key" json:"id_user" xml:"id_user"`
}
