//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Cart struct {
	IDCart int64 `sql:"primary_key" json:"id_cart" xml:"id_cart"`
	FkUser int64 `json:"fk_user" xml:"fk_user"`
}
