//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type CartItemLivestreamExternalVariant struct {
	IDCartItemLivestreamExternalVariant int64 `sql:"primary_key" json:"id_cart_item_livestream_external_variant" xml:"id_cart_item_livestream_external_variant"`
	FkCartItem                          int64 `json:"fk_cart_item" xml:"fk_cart_item"`
	FkLivestreamExternalVariant         int64 `json:"fk_livestream_external_variant" xml:"fk_livestream_external_variant"`
}
