//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/jackc/pgtype"
	"time"
)

type ExternalVariant struct {
	IDExternalVariant        int64       `sql:"primary_key" json:"id_external_variant" xml:"id_external_variant"`
	FkExternalShop           int64       `json:"fk_external_shop" xml:"fk_external_shop"`
	FkVariant                *int64      `json:"fk_variant" xml:"fk_variant"`
	ExternalProductIDMapping *string     `json:"external_product_id_mapping" xml:"external_product_id_mapping"`
	ExternalIDMapping        string      `json:"external_id_mapping" xml:"external_id_mapping"`
	Sku                      *string     `json:"sku" xml:"sku"`
	Name                     string      `json:"name" xml:"name"`
	Status                   string      `json:"status" xml:"status"`
	Option                   pgtype.JSON `json:"option" xml:"option"`
	Price                    float64    `json:"price" xml:"price"`
	ImageURL                 *string     `json:"image_url" xml:"image_url"`
	CreatedAt                time.Time   `json:"created_at" xml:"created_at"`
	UpdatedAt                time.Time   `json:"updated_at" xml:"updated_at"`
}
