//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type LivestreamExternalVariant struct {
	IDLivestreamExternalVariant int64 `sql:"primary_key" json:"id_livestream_external_variant" xml:"id_livestream_external_variant"`
	FkLivestreamProduct         int64 `json:"fk_livestream_product" xml:"fk_livestream_product"`
	FkExternalVariant           int64 `json:"fk_external_variant" xml:"fk_external_variant"`
	Quantity                    int32 `json:"quantity" xml:"quantity"`
}
