//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/jackc/pgtype"
	"time"
)

type Variant struct {
	IDVariant int64       `sql:"primary_key" json:"id_variant" xml:"id_variant"`
	FkProduct int64       `json:"fk_product" xml:"fk_product"`
	Sku       *string     `json:"sku" xml:"sku"`
	Status    string      `json:"status" xml:"status"`
	Option    pgtype.JSON `json:"option" xml:"option"`
	CreatedAt time.Time   `json:"created_at" xml:"created_at"`
	UpdatedAt time.Time   `json:"updated_at" xml:"updated_at"`
}
