//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	Category = Category.FromSchema(schema)
	Ecommerce = Ecommerce.FromSchema(schema)
	ExternalShop = ExternalShop.FromSchema(schema)
	ExternalShopShopifyAuth = ExternalShopShopifyAuth.FromSchema(schema)
	ExternalVariant = ExternalVariant.FromSchema(schema)
	Livestream = Livestream.FromSchema(schema)
	LivestreamExternalVariant = LivestreamExternalVariant.FromSchema(schema)
	LivestreamProduct = LivestreamProduct.FromSchema(schema)
	Product = Product.FromSchema(schema)
	Shop = Shop.FromSchema(schema)
	User = User.FromSchema(schema)
	Variant = Variant.FromSchema(schema)
}
