//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type CartLivestreamExternalVariant struct {
	IDCartLivestreamExternalVariant int64 `sql:"primary_key" json:"id_cart_livestream_external_variant" xml:"id_cart_livestream_external_variant"`
	FkCart                          int64 `json:"fk_cart" xml:"fk_cart"`
	FkLivestreamExternalVariant     int64 `json:"fk_livestream_external_variant" xml:"fk_livestream_external_variant"`
	Quantity                        int32 `json:"quantity" xml:"quantity"`
}
