//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Ecommerce struct {
	IDEcommerce int16  `sql:"primary_key" json:"id_ecommerce" xml:"id_ecommerce"`
	Name        string `json:"name" xml:"name"`
}
