//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/jackc/pgtype"
	"time"
)

type ExternalVariant struct {
	IDExternalVariant int64       `sql:"primary_key" json:"id_external_variant" xml:"id_external_variant" shopify:"-"`
	FkExternalShop    int64       `json:"fk_external_shop" xml:"fk_external_shop" shopify:"-"`
	FkVariant         *int64      `json:"fk_variant" xml:"fk_variant" shopify:"-"`
	IDExternalProduct *string     `json:"id_external_product" xml:"id_external_product" shopify:"-"`
	IDExternal        string      `json:"id_external" xml:"id_external" shopify:"-"`
	Name              string      `json:"name" xml:"name" shopify:"Title"`
	Sku               *string     `json:"sku" xml:"sku" shopify:"Sku"`
	Stock             *int32      `json:"stock" xml:"stock" shopify:"InventoryQuantity"`
	Option            pgtype.JSON `json:"option" xml:"option" shopify:"-"`
	Price             *float64    `json:"price" xml:"price" shopify:"-"`
	ImageURL          *string     `json:"image_url" xml:"image_url" shopify:"-"`
	CreatedAt         time.Time   `json:"created_at" xml:"created_at" shopify:"-"`
	UpdatedAt         time.Time   `json:"updated_at" xml:"updated_at" shopify:"-"`
}
