//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/jackc/pgx/pgtype"
	"time"
)

type Variant struct {
	IDVariant int64       `sql:"primary_key" json:"id_variant" xml:"id_variant"`
	FkProduct int64       `json:"fk_product" xml:"fk_product"`
	Name      string      `json:"name" xml:"name"`
	Sku       *string     `json:"sku" xml:"sku"`
	Stock     *int32      `json:"stock" xml:"stock"`
	Option    pgtype.JSON `json:"option" xml:"option"`
	Price     *float64    `json:"price" xml:"price"`
	CreatedAt time.Time   `json:"created_at" xml:"created_at"`
	UpdatedAt time.Time   `json:"updated_at" xml:"updated_at"`
}
