//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package tables

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ShopifyExternalShopAuth = newShopifyExternalShopAuthTable("public", "shopify_external_shop_auth", "")

type shopifyExternalShopAuthTable struct {
	postgres.Table

	// Columns
	IDShopifyExternalShopAuth postgres.ColumnInteger
	FkExternalShop            postgres.ColumnInteger
	Name                      postgres.ColumnString
	AccessToken               postgres.ColumnString
	CreatedAt                 postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type ShopifyExternalShopAuthTable struct {
	shopifyExternalShopAuthTable

	EXCLUDED shopifyExternalShopAuthTable
}

// AS creates new ShopifyExternalShopAuthTable with assigned alias
func (a ShopifyExternalShopAuthTable) AS(alias string) *ShopifyExternalShopAuthTable {
	return newShopifyExternalShopAuthTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ShopifyExternalShopAuthTable with assigned schema name
func (a ShopifyExternalShopAuthTable) FromSchema(schemaName string) *ShopifyExternalShopAuthTable {
	return newShopifyExternalShopAuthTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ShopifyExternalShopAuthTable with assigned table prefix
func (a ShopifyExternalShopAuthTable) WithPrefix(prefix string) *ShopifyExternalShopAuthTable {
	return newShopifyExternalShopAuthTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ShopifyExternalShopAuthTable with assigned table suffix
func (a ShopifyExternalShopAuthTable) WithSuffix(suffix string) *ShopifyExternalShopAuthTable {
	return newShopifyExternalShopAuthTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newShopifyExternalShopAuthTable(schemaName, tableName, alias string) *ShopifyExternalShopAuthTable {
	return &ShopifyExternalShopAuthTable{
		shopifyExternalShopAuthTable: newShopifyExternalShopAuthTableImpl(schemaName, tableName, alias),
		EXCLUDED:                     newShopifyExternalShopAuthTableImpl("", "excluded", ""),
	}
}

func newShopifyExternalShopAuthTableImpl(schemaName, tableName, alias string) shopifyExternalShopAuthTable {
	var (
		IDShopifyExternalShopAuthColumn = postgres.IntegerColumn("id_shopify_external_shop_auth")
		FkExternalShopColumn            = postgres.IntegerColumn("fk_external_shop")
		NameColumn                      = postgres.StringColumn("name")
		AccessTokenColumn               = postgres.StringColumn("access_token")
		CreatedAtColumn                 = postgres.TimestampColumn("created_at")
		allColumns                      = postgres.ColumnList{IDShopifyExternalShopAuthColumn, FkExternalShopColumn, NameColumn, AccessTokenColumn, CreatedAtColumn}
		mutableColumns                  = postgres.ColumnList{FkExternalShopColumn, NameColumn, AccessTokenColumn, CreatedAtColumn}
	)

	return shopifyExternalShopAuthTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		IDShopifyExternalShopAuth: IDShopifyExternalShopAuthColumn,
		FkExternalShop:            FkExternalShopColumn,
		Name:                      NameColumn,
		AccessToken:               AccessTokenColumn,
		CreatedAt:                 CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
