import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./store_provider";
import ThemeProvider from "./theme_provider";
import { Layout } from "antd";
import Sider from "@/component/core/Sider";
import Header from "@/component/core/Header";
import Content from "@/component/core/Content";
import { App } from "antd";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <ThemeProvider>
            <App>
              <Layout hasSider>
                <Sider />
                <Layout>
                  <Header />
                  <Content>{children}</Content>
                </Layout>
              </Layout>
            </App>
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
