// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"ecommerce/api/handler"
	"ecommerce/internal/adapter"
	"ecommerce/internal/configs"
	"ecommerce/internal/database"
	"ecommerce/internal/repository"
	"ecommerce/internal/server"
	"ecommerce/internal/service"
)

// Injectors from wire.go:

//go:generate wire -package=cmd
func initServer() server.IServer {
	config := configs.NewConfig()
	postgresqlDatabase := database.NewPostgresDatabase(config)
	iProductRepository := repository.NewProductRepository(postgresqlDatabase)
	iVariantRepository := repository.NewVariantRepository(postgresqlDatabase)
	iExternalVariantRepository := repository.NewExternalVariantRepository(postgresqlDatabase)
	iShopifyAdapter := adapter.NewShopifyAdapter(config)
	iExternalShopRepository := repository.NewExternalShopRepository(postgresqlDatabase)
	iExternalShopShopifyAuthRepository := repository.NewExternalShopShopifyAuthRepository(postgresqlDatabase)
	iShopifyService := service.NewShopifyService(iShopifyAdapter, iProductRepository, iVariantRepository, iExternalShopRepository, iExternalShopShopifyAuthRepository, iExternalVariantRepository)
	v := service.ProvideEcommerceServices(iShopifyService)
	iProductService := service.NewProductService(iProductRepository, iVariantRepository, iExternalVariantRepository, v)
	iProductHandler := handler.NewProductHandler(iProductService)
	iVariantService := service.NewVariantService(iVariantRepository, v)
	iVariantHandler := handler.NewVariantHandler(iProductService, iVariantService)
	iShopifyHandler := handler.NewShopifyHandler(iShopifyService)
	iExternalShopService := service.NewExternalShopService(iExternalShopRepository, v)
	iExternalShopHandler := handler.NewExternalShopHandler(iExternalShopService)
	iExternalProductService := service.NewExternalProductService(v, iExternalShopService)
	iExternalProductHandler := handler.NewExternalProductHandler(iExternalProductService)
	iLivestreamRepository := repository.NewLivestreamRepository(postgresqlDatabase)
	iLivestreamProductRepository := repository.NewLivestreamProductRepository(postgresqlDatabase)
	iLivestreamExternalVariantRepository := repository.NewLivestreamExternalVariantRepository(postgresqlDatabase)
	iLivestreamService := service.NewLivestreamService(iLivestreamRepository, iLivestreamProductRepository, iLivestreamExternalVariantRepository)
	iLivestreamHandler := handler.NewLivestreamHandler(iLivestreamService)
	iLivestreamProductService := service.NewLivestreamProductService(iLivestreamProductRepository, iLivestreamExternalVariantRepository)
	iLivestreamProductHandler := handler.NewLivestreamProductHandler(iLivestreamProductService)
	iCartRepository := repository.NewCartRepository(postgresqlDatabase)
	iCartService := service.NewCartService(iCartRepository)
	iCartHandler := handler.NewCartHandler(iCartService)
	handlers := handler.ProvideHandlers(iProductHandler, iVariantHandler, iShopifyHandler, iExternalShopHandler, iExternalProductHandler, iLivestreamHandler, iLivestreamProductHandler, iCartHandler)
	iServer := server.NewServer(config, handlers)
	return iServer
}
