//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ExternalShopShopifyAuth = newExternalShopShopifyAuthTable("public", "external_shop_shopify_auth", "")

type externalShopShopifyAuthTable struct {
	postgres.Table

	// Columns
	IDExternalShopShopifyAuth postgres.ColumnInteger
	FkExternalShop            postgres.ColumnInteger
	Name                      postgres.ColumnString
	AccessToken               postgres.ColumnString
	CreatedAt                 postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type ExternalShopShopifyAuthTable struct {
	externalShopShopifyAuthTable

	EXCLUDED externalShopShopifyAuthTable
}

// AS creates new ExternalShopShopifyAuthTable with assigned alias
func (a ExternalShopShopifyAuthTable) AS(alias string) *ExternalShopShopifyAuthTable {
	return newExternalShopShopifyAuthTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ExternalShopShopifyAuthTable with assigned schema name
func (a ExternalShopShopifyAuthTable) FromSchema(schemaName string) *ExternalShopShopifyAuthTable {
	return newExternalShopShopifyAuthTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ExternalShopShopifyAuthTable with assigned table prefix
func (a ExternalShopShopifyAuthTable) WithPrefix(prefix string) *ExternalShopShopifyAuthTable {
	return newExternalShopShopifyAuthTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ExternalShopShopifyAuthTable with assigned table suffix
func (a ExternalShopShopifyAuthTable) WithSuffix(suffix string) *ExternalShopShopifyAuthTable {
	return newExternalShopShopifyAuthTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newExternalShopShopifyAuthTable(schemaName, tableName, alias string) *ExternalShopShopifyAuthTable {
	return &ExternalShopShopifyAuthTable{
		externalShopShopifyAuthTable: newExternalShopShopifyAuthTableImpl(schemaName, tableName, alias),
		EXCLUDED:                     newExternalShopShopifyAuthTableImpl("", "excluded", ""),
	}
}

func newExternalShopShopifyAuthTableImpl(schemaName, tableName, alias string) externalShopShopifyAuthTable {
	var (
		IDExternalShopShopifyAuthColumn = postgres.IntegerColumn("id_external_shop_shopify_auth")
		FkExternalShopColumn            = postgres.IntegerColumn("fk_external_shop")
		NameColumn                      = postgres.StringColumn("name")
		AccessTokenColumn               = postgres.StringColumn("access_token")
		CreatedAtColumn                 = postgres.TimestampColumn("created_at")
		allColumns                      = postgres.ColumnList{IDExternalShopShopifyAuthColumn, FkExternalShopColumn, NameColumn, AccessTokenColumn, CreatedAtColumn}
		mutableColumns                  = postgres.ColumnList{FkExternalShopColumn, NameColumn, AccessTokenColumn, CreatedAtColumn}
	)

	return externalShopShopifyAuthTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		IDExternalShopShopifyAuth: IDExternalShopShopifyAuthColumn,
		FkExternalShop:            FkExternalShopColumn,
		Name:                      NameColumn,
		AccessToken:               AccessTokenColumn,
		CreatedAt:                 CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
