//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type ExternalShopShopifyAuth struct {
	IDExternalShopShopifyAuth int64     `sql:"primary_key" json:"id_external_shop_shopify_auth" xml:"id_external_shop_shopify_auth"`
	FkExternalShop            int64     `json:"fk_external_shop" xml:"fk_external_shop"`
	Name                      string    `json:"name" xml:"name"`
	AccessToken               *string   `json:"access_token" xml:"access_token"`
	CreatedAt                 time.Time `json:"created_at" xml:"created_at"`
}
