//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/jackc/pgtype"
	"time"
)

type ExternalProductShopify struct {
	IDExternalProductShopify int64       `sql:"primary_key" json:"id_external_product_shopify" xml:"id_external_product_shopify" shopify:"-"`
	FkExternalShop           int64       `json:"fk_external_shop" xml:"fk_external_shop" shopify:"-"`
	FkProduct                *int64      `json:"fk_product" xml:"fk_product" shopify:"-"`
	FkVariant                *int64      `json:"fk_variant" xml:"fk_variant" shopify:"-"`
	ShopifyProductID         int64       `json:"shopify_product_id" xml:"shopify_product_id" shopify:"ProductID"`
	ShopifyVariantID         int64       `json:"shopify_variant_id" xml:"shopify_variant_id" shopify:"ID"`
	Name                     string      `json:"name" xml:"name" shopify:"Title"`
	Sku                      *string     `json:"sku" xml:"sku" shopify:"Sku"`
	Stock                    *int32      `json:"stock" xml:"stock" shopify:"InventoryQuantity"`
	Option                   pgtype.JSON `json:"option" xml:"option" shopify:"-"`
	Price                    *float64    `json:"price" xml:"price" shopify:"-"`
	ImageURL                 *string     `json:"image_url" xml:"image_url" shopify:"-"`
	CreatedAt                time.Time   `json:"created_at" xml:"created_at" shopify:"-"`
	UpdatedAt                time.Time   `json:"updated_at" xml:"updated_at" shopify:"-"`
}
