//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Shop struct {
	IDShop      int64     `sql:"primary_key" json:"id_shop" xml:"id_shop"`
	FkUser      int64     `json:"fk_user" xml:"fk_user"`
	Name        string    `json:"name" xml:"name"`
	Description *string   `json:"description" xml:"description"`
	CreatedAt   time.Time `json:"created_at" xml:"created_at"`
	UpdatedAt   time.Time `json:"updated_at" xml:"updated_at"`
}
